# -*- coding: utf-8 -*-
"""BI_TP3_imen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwIGpiacZaKgfsmVWQL4e0UVWW9vKiGC
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df=pd.read_csv("/content/sample_data/Students_Mental_Health - Student Mental health (1).csv")
df.head()

df.columns

df.isnull().sum()

df.head()

#doublons=df[df.duplicated(subset="StudentID").sum()]
df=df.drop_duplicates(subset="StudentID",keep="first")

df[df["Gender"]=="Female"]

#def categorise_Age(x):
#df["Student_Health"]=df["Age"].apply(categorise_Age) #ou bien
bins=[15,20,25,30,float('inf')]
labels=["15-20","21-25","26-30","30+"]
df["Student_Health"]=pd.cut(df["Age"],bins=bins,labels=labels,right=False)

import sqlite3

# Connexion à la base de données (créée si elle n'existe pas)
conn = sqlite3.connect('mydatabase.db')

# Création du curseur  comme pointeur
cursor = conn.cursor()

# Création de la table
cursor.execute('''
CREATE TABLE IF NOT EXISTS StudentInfo (
    StudentID INTEGER PRIMARY KEY,
    Gender TEXT,
    Age INTEGER,
    Course TEXT,
    YearOfStudy Text,
    MaritalStatus Text
)
''')

# Validation des changements
conn.commit()

# Fermeture de la connexion
#conn.close()

import sqlite3

# Connexion à la base existante
conn = sqlite3.connect('mydatabase.db')
cursor = conn.cursor()

# Vérifie le contenu de la table
cursor.execute("SELECT * FROM StudentInfo")

# Récupère toutes les lignes
rows = cursor.fetchall()

# Affiche les résultats
if len(rows) == 0:
    print("Aucune donnée trouvée dans la table 'StudentInfo'.")
else:
    for row in rows:
        print(row)

# Ferme la connexion
#conn.close()

df.head()

for index,row in df.iterrows():
  cursor.execute('''
  insert into StudentInfo (StudentID,Gender,Age,Course,YearOfStudy,MaritalStatus)
  values(?,?,?,?,?,?)
  ''', (row["StudentID"],row["Gender"],row["Age"],row["Specialty"],row["Current_Year_Study"],row["Marital_status"] ))
  conn.commit()
  cursor.execute("SELECT * FROM StudentInfo")
  results = cursor.fetchall()
  for row in results:
    print(row)

cursor.execute('''
  CREATE TABLE IF NOT EXISTS StudentMentalHealth (
    Timestamp TEXT,
    StudentID INTEGER,
    CGPA float,
    Depression TEXT,
    Anxiety TEXT,
    PanicAttack TEXT,
    SeekTreatment TEXT,
    FOREIGN KEY (StudentID) REFERENCES StudentInfo(StudentID)
  )
''')
conn.commit()

df.columns

for index,row in df.iterrows():
  cursor.execute('''
  insert into StudentMentalHealth (Timestamp,StudentID,CGPA,Depression,Anxiety,PanicAttack,SeekTreatment)
  values(?,?,?,?,?,?,?),
  ''', (row["Timestamp"],row["StudentID"],row["CGPA"],row["Depression"],row["Anxiety"],row["Panic_attack"],row["Treatment"]))
  conn.commit()

cursor.execute("""
   select * from StudentInfo
   join StudentMentalHealth on StudentInfo.StudentID=StudentMentalHealth.StudentID where Depression ="Yes"
""")
results=cursor.fetchall()
for row in results:
  print(row)

cursor ("""
    select count(*) from StudentInfo  where Depression ="Yes" and  SeekTreatment="Yes"
""")
results=cursor.fetchone()[0]

cursor("""
   select 100*sum(case when Depression ="Yes" then 1 else 0 end)/count(*) from StudentMentalHealth
   join StudentMentalHealth on StudentMentalHealth.StudentID=StudentInfo.StudentID
   groupnby course
""")

results=cursor.fetchall
for row in results:
  print(row)